version: "3.9"

services:
  api:
    container_name: api
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_HOST=db
      - PG_PORT=5432
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  client:
    build: ./client
    container_name: client
    command: yarn dev
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db

volumes:
  pgdata: {}
